export about from './components/About'
export collection from './components/Collection'
export favs from './containers/Favs'
export loading from './redux/Loading'
export home from './containers/Home'
export detail from './containers/Detail'
export pricelist from './components/Pricelist/Pricelist'
