export { default as about } from './components/About'
export { default as contact } from './components/Contact'
// export { default as favs } from './containers/Favs'
export { default as loading } from './redux/Loading'
export { default as home } from './containers/Home'
export { default as detail } from './containers/Detail'
// export { default as itemEdit } from './containers/ItemEdit'
export { default as pricelist } from './components/Pricelist/Pricelist'
export { default as project } from './containers/Project'
export { default as projects } from './components/Fav/Projects'
export { default as login } from './containers/Login'
export { default as showroom } from './containers/Showroom'
