export about from './components/About'
export contact from './components/Contact'
// export favs from './containers/Favs'
export loading from './redux/Loading'
export home from './containers/Home'
export detail from './containers/Detail'
// export itemEdit from './containers/ItemEdit'
export pricelist from './components/Pricelist/Pricelist'
export project from './containers/Project'
export login from './containers/Login'
export showroom from './containers/Showroom'
